bias:
  long_name: Bias or MSD
  name: Bias
  value: -1.0454410083954362
corr:
  long_name: Pearson product-moment correlation coefficient
  name: Correlation Coefficient
  value: 0.968337662735362
descriptive_model:
  long_name: Max, Min, Mean, Standard Deviation (Model)
  name: Descriptive Statistics (Model)
  value:
  - 10.182136902209258
  - 2.115196588053263
  - 6.461352545054106
  - 2.3277905068236424
descriptive_obs:
  long_name: Max, Min, Mean, Standard Deviation (Observation)
  name: Descriptive Statistics (Observation)
  value:
  - 11.73410524428034
  - 3.1757058954030315
  - 7.506637512281986
  - 2.314566203057724
dist:
  long_name: Distance in km from data location to selected model location
  name: Distance
  value: 0.45826141628399714
ioa:
  long_name: Index of Agreement (Willmott 1981)
  name: Index of Agreement
  value: 0.9360448401162721
mse:
  long_name: Mean Squared Error (MSE)
  name: Mean Squared Error
  value: 0.34134803910859207
rmse:
  long_name: Root Mean Square Error (RMSE)
  name: RMSE
  value: 0.5842499799816788
rmse_uncentered:
  long_name: Root Mean Square Error (RMSE), uncentered
  name: RMSE
  value: 1.1976205228679961
ss:
  long_name: Skill Score (Taylor 2001)
  name: Skill Score
  value: 0.9843339903886963
ss_orig:
  long_name: Skill Score (Bogden 1996)
  name: Murphy Skill Score
  value: 0.7322799468687171
