bias:
  long_name: Bias or MSD
  name: Bias
  value: -0.9541366143098835
corr:
  long_name: Pearson product-moment correlation coefficient
  name: Correlation Coefficient
  value: 0.703666255486864
descriptive_model:
  long_name: Max, Min, Mean, Standard Deviation (Model)
  name: Descriptive Statistics (Model)
  value:
  - 10.596504100163777
  - 7.165994135538737
  - 9.191703855734948
  - 0.7678479390533264
descriptive_obs:
  long_name: Max, Min, Mean, Standard Deviation (Observation)
  name: Descriptive Statistics (Observation)
  value:
  - 12.0616
  - 8.3482
  - 10.14584047004483
  - 0.7385792126298247
dist:
  long_name: Distance in km from data location to selected model location
  name: Distance
  value: 0.45826141628399714
ioa:
  long_name: Index of Agreement (Willmott 1981)
  name: Index of Agreement
  value: 0.6227973977164522
mse:
  long_name: Mean Squared Error (MSE)
  name: Mean Squared Error
  value: 0.33696818594164046
rmse:
  long_name: Root Mean Square Error (RMSE)
  name: RMSE
  value: 0.5804896088145252
rmse_uncentered:
  long_name: Root Mean Square Error (RMSE), uncentered
  name: RMSE
  value: 1.1168459449307984
ss:
  long_name: Skill Score (Taylor 2001)
  name: Skill Score
  value: 0.8507224760014999
ss_orig:
  long_name: Skill Score (Bogden 1996)
  name: Murphy Skill Score
  value: -1.2866114978095489
