bias:
  long_name: Bias or MSD
  name: Bias
  value: 1.785892524701169
corr:
  long_name: Pearson product-moment correlation coefficient
  name: Correlation Coefficient
  value: 0.5532514976985817
descriptive_model:
  long_name: Max, Min, Mean, Standard Deviation (Model)
  name: Descriptive Statistics (Model)
  value:
  - 31.935314051310222
  - 30.955965296427408
  - 31.511135059682825
  - 0.2125088278219566
descriptive_obs:
  long_name: Max, Min, Mean, Standard Deviation (Observation)
  name: Descriptive Statistics (Observation)
  value:
  - 31.1455
  - 28.5083
  - 29.72524253498166
  - 0.6085169885502
dist:
  long_name: Distance in km from data location to selected model location
  name: Distance
  value: 0.45826141628399714
ioa:
  long_name: Index of Agreement (Willmott 1981)
  name: Index of Agreement
  value: 0.36353189021870025
mse:
  long_name: Mean Squared Error (MSE)
  name: Mean Squared Error
  value: 0.2723652357571297
rmse:
  long_name: Root Mean Square Error (RMSE)
  name: RMSE
  value: 0.5218862287483065
rmse_uncentered:
  long_name: Root Mean Square Error (RMSE), uncentered
  name: RMSE
  value: 1.8605852158771568
ss:
  long_name: Skill Score (Taylor 2001)
  name: Skill Score
  value: 0.3010011723662252
ss_orig:
  long_name: Skill Score (Bogden 1996)
  name: Murphy Skill Score
  value: -8.348753671783705
