bias:
  long_name: Bias or MSD
  name: Bias
  value: -1.0428064557603138
corr:
  long_name: Pearson product-moment correlation coefficient
  name: Correlation Coefficient
  value: 0.9640140636953739
descriptive_model:
  long_name: Max, Min, Mean, Standard Deviation (Model)
  name: Descriptive Statistics (Model)
  value:
  - 10.667766936620076
  - 1.9776113311449686
  - 6.4401400833599505
  - 2.334689621232096
descriptive_obs:
  long_name: Max, Min, Mean, Standard Deviation (Observation)
  name: Descriptive Statistics (Observation)
  value:
  - 11.8224
  - 2.6316
  - 7.482946539120265
  - 2.327297454066292
dist:
  long_name: Distance in km from data location to selected model location
  name: Distance
  value: 0.45826141628399714
ioa:
  long_name: Index of Agreement (Willmott 1981)
  name: Index of Agreement
  value: 0.9344599206357792
mse:
  long_name: Mean Squared Error (MSE)
  name: Mean Squared Error
  value: 0.3911150527037122
rmse:
  long_name: Root Mean Square Error (RMSE)
  name: RMSE
  value: 0.6253919192823907
rmse_uncentered:
  long_name: Root Mean Square Error (RMSE), uncentered
  name: RMSE
  value: 1.2159606724228789
ss:
  long_name: Skill Score (Taylor 2001)
  name: Skill Score
  value: 0.9821937244186887
ss_orig:
  long_name: Skill Score (Bogden 1996)
  name: Murphy Skill Score
  value: 0.7270172095210106
