bias:
  long_name: Bias or MSD
  name: Bias
  value: 1.3475299156887095
corr:
  long_name: Pearson product-moment correlation coefficient
  name: Correlation Coefficient
  value: 0.5827427817303699
descriptive_model:
  long_name: Max, Min, Mean, Standard Deviation (Model)
  name: Descriptive Statistics (Model)
  value:
  - 32.08271212617257
  - 31.338840133590274
  - 31.738759696878667
  - 0.17377664781979574
descriptive_obs:
  long_name: Max, Min, Mean, Standard Deviation (Observation)
  name: Descriptive Statistics (Observation)
  value:
  - 31.768419174757284
  - 28.817729438592547
  - 30.391253153354487
  - 0.850100997725466
dist:
  long_name: Distance in km from data location to selected model location
  name: Distance
  value: 0.45826141628399714
ioa:
  long_name: Index of Agreement (Willmott 1981)
  name: Index of Agreement
  value: 0.4722390347352057
mse:
  long_name: Mean Squared Error (MSE)
  name: Mean Squared Error
  value: 0.5807110192510301
rmse:
  long_name: Root Mean Square Error (RMSE)
  name: RMSE
  value: 0.7620439746176267
rmse_uncentered:
  long_name: Root Mean Square Error (RMSE), uncentered
  name: RMSE
  value: 1.5480787746044424
ss:
  long_name: Skill Score (Taylor 2001)
  name: Skill Score
  value: 0.12189733153426731
ss_orig:
  long_name: Skill Score (Bogden 1996)
  name: Murphy Skill Score
  value: -2.316093126739215
