bias:
  long_name: Bias or MSD
  name: Bias
  value: -0.9596103787794169
corr:
  long_name: Pearson product-moment correlation coefficient
  name: Correlation Coefficient
  value: 0.7939453708373689
descriptive_model:
  long_name: Max, Min, Mean, Standard Deviation (Model)
  name: Descriptive Statistics (Model)
  value:
  - 10.41925449941831
  - 7.424851645691497
  - 9.217740700671142
  - 0.7290163152889143
descriptive_obs:
  long_name: Max, Min, Mean, Standard Deviation (Observation)
  name: Descriptive Statistics (Observation)
  value:
  - 11.743648922604992
  - 8.758032025465134
  - 10.177151194763516
  - 0.6532714087763549
dist:
  long_name: Distance in km from data location to selected model location
  name: Distance
  value: 0.45826141628399714
ioa:
  long_name: Index of Agreement (Willmott 1981)
  name: Index of Agreement
  value: 0.6260482293263012
mse:
  long_name: Mean Squared Error (MSE)
  name: Mean Squared Error
  value: 0.2019770576316518
rmse:
  long_name: Root Mean Square Error (RMSE)
  name: RMSE
  value: 0.44941857731034196
rmse_uncentered:
  long_name: Root Mean Square Error (RMSE), uncentered
  name: RMSE
  value: 1.0596363039925254
ss:
  long_name: Skill Score (Taylor 2001)
  name: Skill Score
  value: 0.8864547092927051
ss_orig:
  long_name: Skill Score (Bogden 1996)
  name: Murphy Skill Score
  value: -1.6306627994280314
