bias:
  long_name: Bias or MSD
  name: Bias
  value: 1.7996125069505522
corr:
  long_name: Pearson product-moment correlation coefficient
  name: Correlation Coefficient
  value: 0.7244336952071345
descriptive_model:
  long_name: Max, Min, Mean, Standard Deviation (Model)
  name: Descriptive Statistics (Model)
  value:
  - 31.835573521618528
  - 31.125981227912835
  - 31.50598179694673
  - 0.1970694914023324
descriptive_obs:
  long_name: Max, Min, Mean, Standard Deviation (Observation)
  name: Descriptive Statistics (Observation)
  value:
  - 30.92284919393735
  - 28.618611431132937
  - 29.706348405311672
  - 0.5336536768723292
dist:
  long_name: Distance in km from data location to selected model location
  name: Distance
  value: 0.45826141628399714
ioa:
  long_name: Index of Agreement (Willmott 1981)
  name: Index of Agreement
  value: 0.3451983313320416
mse:
  long_name: Mean Squared Error (MSE)
  name: Mean Squared Error
  value: 0.1712769159875712
rmse:
  long_name: Root Mean Square Error (RMSE)
  name: RMSE
  value: 0.4138561537389183
rmse_uncentered:
  long_name: Root Mean Square Error (RMSE), uncentered
  name: RMSE
  value: 1.8465866052596214
ss:
  long_name: Skill Score (Taylor 2001)
  name: Skill Score
  value: 0.36424777403933717
ss_orig:
  long_name: Skill Score (Bogden 1996)
  name: Murphy Skill Score
  value: -10.971792400369127
